### ISSUE TITLE
Is the current release broken against current scipy/numba?

### ISSUE THREAD

**Issue by adeak** [numba/numba-scipy#44]
I can't get the package to work in the most basic scenario. To be on the safe side I also tried [the example from a numba 0.46 demo notebook linked in another issue](https://mybinder.org/v2/gh/numba/numba-examples/master?filepath=notebooks/Numba_046_release_demo.ipynb):
```py
from numba import njit
from scipy import special

@njit
def call_scipy_in_jitted_code():
    print("special.beta(1.2, 3.4)", special.beta(1.2, 3.4))
    print("special.j0(5.6)       ", special.j0(5.6))
    
call_scipy_in_jitted_code()
```

The result is an error as if `numba-scipy` wasn't even installed:
```
TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Unknown attribute 'beta' of type Module(<module 'scipy.special' from '/home/user/virtualenvs/py3.8_main/lib/python3.8/site-packages/scipy/special/__init__.py'>)

File "<ipython-input-1-995b33e9a9f1>", line 6:
def call_scipy_in_jitted_code():
    print("special.beta(1.2, 3.4)", special.beta(1.2, 3.4))
    ^

During: typing of get attribute at <ipython-input-1-995b33e9a9f1> (6)

File "<ipython-input-1-995b33e9a9f1>", line 6:
def call_scipy_in_jitted_code():
    print("special.beta(1.2, 3.4)", special.beta(1.2, 3.4))
    ^
```

The relevant part of my `pip freeze` in the virtualenv:
```
$ pip freeze |grep -E 'numba|scipy'
numba==0.51.0
numba-scipy==0.2.0
scipy==1.5.2
```

Am I doing anything wrong?

**Comment by rsarkar-github** [comment]
When will this issue be fixed?

**Comment by esc** [comment]
@rsarkar-github thank you for asking about this. From what I understand this is stalled on #37 and/or #54 -- so I assume this will be fixed once we can stabilize the code.

**Comment by adeak** [comment]
@esc thanks, that's useful to know :P

**Comment by esc** [comment]
@rsarkar-github @adeak if you have time and inclination, more eyeballs 👀 on #54 would be great. For example, check if #54 will enable the snippet in this issue to run? That would be most useful. The plan here is to release a new version of numba-scipy as soon as the Scipy compatibility versions have been resolved. Thank you in advance!

**Comment by adeak** [comment]
@esc I'm still seeing the same error with the branch from https://github.com/numba/numba-scipy/pull/54:
```
$ pip freeze
llvmlite==0.36.0
numba==0.53.1
numba-scipy==0.3.0.dev0+22.gb1255eb
numpy==1.20.2
scipy==1.6.2
```

Should I try installing scipy and/or numba from source perhaps?

**Comment by esc** [comment]
> Should I try installing scipy and/or numba from source perhaps?

I am doubtful that this will help. I will take a closer look myself shortly.

**Comment by esc** [comment]
@adeak I can reproduce this with the following setup:

```
 💣 zsh» conda list | grep "numba\|llvmlite\|scipy\|numba-scipy"
# packages in environment at /Users/vhaenel/miniconda3/envs/numba-scipy:
llvmlite                  0.36.0           py39he4411ff_4    defaults
numba                     0.53.1           py39hb2f4e1b_0    defaults
numba-scipy               0.3.0.dev0+24.g7ba7cbdd81           dev_0    <develop>
scipy                     1.6.1            py39h4420a3a_0    defaults
```

**Comment by adeak** [comment]
Oh crap, I just noticed that I was using master from that branch, not the PR branch. Ugh. "Fortunately" it still errors :sweat_smile: Sorry about the mess.

**Comment by esc** [comment]
@adeak ah yes, I was wondering about which commit is `b1255eb` -- thank you for clearing that up and no worries on the mess ☺️

**Comment by esc** [comment]
So, yes, the question is, is `beta` even being generated? And if so, why isn't it being picked up?

**Comment by esc** [comment]
So, the docs do seem to suggest it would be generated: 

https://github.com/numba/numba-scipy/blob/master/docs/source/reference/special.rst#id23

**Comment by adeak** [comment]
Yes, at least in October 2019 it was supposed to work, since my example was taken from https://mybinder.org/v2/gh/numba/numba-examples/master?filepath=notebooks/Numba_046_release_demo.ipynb made for numba 0.46.

**Comment by esc** [comment]
@adeak may I propose to close this issue, since #54 has been merged. Thank you!

**Comment by adeak** [comment]
Yes, of course, thanks for the nudge @esc.
